version: 2.1

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    environment:
      JAVA_OPTS: "-XX:MaxRAMPercentage=50"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    steps:
      - checkout
      - run: echo "building git revision << pipeline.git.revision >>"
  release:

workflows:
  version: 2.1
  build:
    jobs:
      - build