version: 2.1

parameters:
  benchmarks:
    type: boolean
    default: false

executors:
  builder:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    environment:
      JAVA_OPTS: "-XX:MaxRAMPercentage=50"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - run: 
          name: Build
          command: echo "building git revision << pipeline.git.revision >>"
      - when:
          condition:
            equal: [main, << pipeline.git.branch >>]
          steps:
            run:
              name: Main
              command: echo "on main"
      - when:
          condition:
            equal: [ true, << pipeline.parameters.benchmarks >> ]
          steps:
            run:
              name: Benchmarks
              command: echo "running benchmarks"

  release:
    executor: builder
    steps:
      - checkout
      - run: 
          name: Release
          command: echo "releasing << pipeline.git.tag >>"

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
              tags:
                only: /^\d+\.\d+\.\d+$/
      - release:
          filters:
              tags:
                only: /^\d+\.\d+\.\d+$/
              branches:
                ignore: /.*/ 
          requires:
            - build
            